# Generated by Django 5.2 on 2025-05-03 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_status',
            field=models.CharField(choices=[('correct', 'Correct Image'), ('wrong', 'Wrong Image'), ('cover', 'Cover Image')], default='cover', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
