# Generated by Django 5.2 on 2025-05-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_image_status_course_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_status',
        ),
        migrations.CreateModel(
            name='CourseContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/content_blocks/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='app.course')),
            ],
        ),
    ]
