# Generated by Django 5.2 on 2025-05-05 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_course_image_status_coursecontentblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontentblock',
            name='description',
        ),
        migrations.AddField(
            model_name='coursecontentblock',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecontentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_blocks/'),
        ),
        migrations.AlterField(
            model_name='coursecontentblock',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.course')),
            ],
        ),
    ]
